name: Run API Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install project dependencies
      - name: Install Project Dependencies
        run: npm install

      # Start Best Buy API server in background
      - name: Start API Server
        run: |
          npm start &
          sleep 10   # wait for server to start

      # Install Newman
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run Postman Collection
      - name: Run Collection
        run: |
          newman run postman/bestbuy_collection1202.json \
          -e postman/bestbuy_environment1202.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export report.html

      # Upload HTML Report
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: report.html
